---
version: "3"

services:
    redis-db:
        image: redis
        ports:
            - 6379:6379
        volumes:
            - ./data:/data
        command: ["--save", "1", "1"]
    flask-app:
        build:
            context: ./
            dockerfile: ./Dockerfile
        depends_on:
            - redis-db
        image: flask-app
        ports:
            - 3000:3000
        volumes:
            - ./config.yaml:/config.yaml