---
version: "3"

services:
    flask-app:
        build:
            context: ./
            dockerfile: ./Dockerfile
        image: charan427/iss-tracker:1.0
        container_name: iss-tracker
        ports:
            - "3000:3000"